# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Profidicator' do
    pod 'Charts'
    pod 'Charts/Realm'
end

target 'ProfidicatorTests' do

end

target 'ProfidicatorUITests' do

end

